import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import cloudflare from '@astrojs/cloudflare';

export default defineConfig({
  site: 'https://opnchat.net',
  output: 'server',
  adapter: cloudflare(),
  prefetch: {
    defaultStrategy: 'viewport',
  },
  trailingSlash: 'always',
  // 301 redirects for legacy URLs that Google found as 404s
  // These are handled natively by Astro + Cloudflare adapter (generates _redirects + _routes.json)
  // Also backed up by src/middleware.ts for server-side handling
  redirects: {
    // Old "converter" slug → correct "unit-converter"
    '/converter': '/unit-converter/',
    '/converter/': '/unit-converter/',
    '/es/converter': '/es/unit-converter/',
    '/es/converter/': '/es/unit-converter/',
    '/pt/converter': '/pt/unit-converter/',
    '/pt/converter/': '/pt/unit-converter/',
    '/id/converter': '/id/unit-converter/',
    '/id/converter/': '/id/unit-converter/',
    '/ru/converter': '/ru/unit-converter/',
    '/ru/converter/': '/ru/unit-converter/',
    '/de/converter': '/de/unit-converter/',
    '/de/converter/': '/de/unit-converter/',
    '/ar/converter': '/ar/unit-converter/',
    '/ar/converter/': '/ar/unit-converter/',
    // Old "eng" prefix → default locale (no prefix)
    '/eng': '/',
    '/eng/': '/',
    '/eng/whatsapp': '/whatsapp/',
    '/eng/whatsapp/': '/whatsapp/',
    '/eng/telegram': '/telegram/',
    '/eng/telegram/': '/telegram/',
    '/eng/wa-link': '/wa-link/',
    '/eng/wa-link/': '/wa-link/',
    '/eng/wa-widget': '/wa-widget/',
    '/eng/wa-widget/': '/wa-widget/',
    '/eng/tg-link': '/tg-link/',
    '/eng/tg-link/': '/tg-link/',
    '/eng/qr-code': '/qr-code/',
    '/eng/qr-code/': '/qr-code/',
    '/eng/password': '/password/',
    '/eng/password/': '/password/',
    '/eng/unit-converter': '/unit-converter/',
    '/eng/unit-converter/': '/unit-converter/',
    '/eng/whatsapp-text-formatter': '/whatsapp-text-formatter/',
    '/eng/whatsapp-text-formatter/': '/whatsapp-text-formatter/',
    '/eng/fancy-text': '/fancy-text/',
    '/eng/fancy-text/': '/fancy-text/',
    '/eng/word-counter': '/word-counter/',
    '/eng/word-counter/': '/word-counter/',
    '/eng/notepad': '/notepad/',
    '/eng/notepad/': '/notepad/',
    '/eng/timezone': '/timezone/',
    '/eng/timezone/': '/timezone/',
    '/eng/emoji-picker': '/emoji-picker/',
    '/eng/emoji-picker/': '/emoji-picker/',
    '/eng/disclaimer': '/disclaimer/',
    '/eng/disclaimer/': '/disclaimer/',
    '/eng/privacy': '/privacy/',
    '/eng/privacy/': '/privacy/',
    '/eng/blog': '/blog/',
    '/eng/blog/': '/blog/',
    // Old "en" prefix (en is default, should be at root without prefix)
    '/en': '/',
    '/en/': '/',
    '/en/whatsapp': '/whatsapp/',
    '/en/whatsapp/': '/whatsapp/',
    '/en/telegram': '/telegram/',
    '/en/telegram/': '/telegram/',
    '/en/wa-link': '/wa-link/',
    '/en/wa-link/': '/wa-link/',
    '/en/wa-widget': '/wa-widget/',
    '/en/wa-widget/': '/wa-widget/',
    '/en/tg-link': '/tg-link/',
    '/en/tg-link/': '/tg-link/',
    '/en/qr-code': '/qr-code/',
    '/en/qr-code/': '/qr-code/',
    '/en/password': '/password/',
    '/en/password/': '/password/',
    '/en/unit-converter': '/unit-converter/',
    '/en/unit-converter/': '/unit-converter/',
    '/en/whatsapp-text-formatter': '/whatsapp-text-formatter/',
    '/en/whatsapp-text-formatter/': '/whatsapp-text-formatter/',
    '/en/fancy-text': '/fancy-text/',
    '/en/fancy-text/': '/fancy-text/',
    '/en/word-counter': '/word-counter/',
    '/en/word-counter/': '/word-counter/',
    '/en/notepad': '/notepad/',
    '/en/notepad/': '/notepad/',
    '/en/timezone': '/timezone/',
    '/en/timezone/': '/timezone/',
    '/en/emoji-picker': '/emoji-picker/',
    '/en/emoji-picker/': '/emoji-picker/',
    '/en/disclaimer': '/disclaimer/',
    '/en/disclaimer/': '/disclaimer/',
    '/en/privacy': '/privacy/',
    '/en/privacy/': '/privacy/',
    '/en/blog': '/blog/',
    '/en/blog/': '/blog/',
  },
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es', 'pt', 'id', 'ru', 'de', 'ar'],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  integrations: [
    sitemap({
      i18n: {
        defaultLocale: 'en',
        locales: {
          en: 'en-US',
          es: 'es-ES',
          pt: 'pt-BR',
          id: 'id-ID',
          ru: 'ru-RU',
          de: 'de-DE',
          ar: 'ar-SA',
        },
      },
    }),
  ],
});
